-- Misconception codes added with the measures question templates (clock reading, ruler start, volume).
--
-- The whole registry is upserted, so this migration is safe to run on a database that already has the
-- earlier codes. It is generated from src/lib/misconceptions/registry.ts
-- (`npx tsx scripts/misconceptions-sql.ts`); tests/db/misconceptions.test.ts keeps the two identical.
-- A question's misconception tags are validated against this table by a trigger (migration 0014).

insert into public.misconceptions (code, name, description, topic_code, remediation) values
  ('PLACE_VALUE_CONFUSION', 'Place value confusion', 'Gives the digit instead of its value, or reads a digit''s position wrongly (for example says the 7 in 4 703 is worth 7).', 'NUM', 'Build the number in a place-value chart and say the value of each digit in words, then compare the digit with its value.'),
  ('CARRYING_ERROR', 'Carrying (regrouping) error in addition', 'Forgets to carry, or carries into the wrong column, when a column adds to ten or more.', 'OPS', 'Add column by column, writing the carried digit above the next column; check each column total before moving on.'),
  ('BORROWING_ERROR', 'Borrowing (regrouping) error in subtraction', 'Subtracts the smaller digit from the larger in every column, or forgets to reduce the next column after borrowing.', 'OPS', 'Rewrite the top number with the regrouped digits and check each column: can the bottom digit be taken from the top digit?'),
  ('FRACTION_DENOMINATOR_CONFUSION', 'Denominator confusion', 'Adds or subtracts denominators as well as numerators, or thinks a bigger denominator means a bigger fraction.', 'NUM', 'Show equal parts of the same whole with a fraction strip; the denominator names the size of the parts, so it is not added.'),
  ('DECIMAL_PLACE_CONFUSION', 'Decimal place confusion', 'Misplaces the decimal point, or compares decimals as if they were whole numbers (thinks 0.35 is bigger than 0.4).', 'NUM', 'Line the numbers up in a place-value chart with tenths, hundredths and thousandths, and compare column by column from the left.'),
  ('UNIT_CONVERSION_ERROR', 'Unit conversion error', 'Multiplies or divides by the wrong power of ten (or the wrong way round) when changing between metric units.', 'MEA', 'Decide first whether the new unit is bigger or smaller (so should the number be bigger or smaller?), then use the conversion fact.'),
  ('TIME_CONVERSION_ERROR', 'Time conversion error', 'Treats time as decimal (100 minutes in an hour) or confuses 12-hour and 24-hour clock times.', 'MEA', 'Use a number line or clock face with 60-minute hours; for 24-hour times count on from 12.'),
  ('AREA_VS_PERIMETER', 'Area and perimeter confused', 'Finds the distance around a shape when asked for the space inside it, or the other way round.', 'MEA', 'Contrast them physically: perimeter is a fence around a field (length), area is the grass inside (squares).'),
  ('ORDER_OF_OPERATIONS_ERROR', 'Order of operations error', 'Works strictly left to right, ignoring that multiplication and division come before addition and subtraction.', 'OPS', 'Underline the multiplication or division first, work it out, then do the additions and subtractions; brackets come before everything.'),
  ('GRAPH_READING_ERROR', 'Graph or table reading error', 'Reads the wrong bar, the wrong axis or the wrong scale step from a graph, or confuses a count with a category.', 'REL', 'Find the label first, follow the bar to the scale with a finger or ruler, and check what one step on the scale is worth.'),
  ('ZERO_PLACEHOLDER_ERROR', 'Zero as a placeholder missed', 'Leaves out a zero when writing a number from its words or expanded form (writes 405 for four thousand and five).', 'NUM', 'Say each place out loud (thousands, hundreds, tens, ones) and write a zero for every empty place.'),
  ('FRACTION_SIZE_BY_DENOMINATOR', 'Bigger denominator, bigger fraction', 'Believes 1/8 is larger than 1/4 because 8 is larger than 4.', 'NUM', 'Share the same whole into equal parts: more parts means smaller parts. Compare with fraction strips.'),
  ('ROUNDING_DIRECTION_ERROR', 'Rounding in the wrong direction', 'Rounds down when the next digit is 5 or more (or rounds up when it is below 5), or looks at the wrong digit.', 'NUM', 'Find the digit to its right: 5 or more rounds up, less than 5 stays. Mark the two possible answers on a number line.'),
  ('BASIC_FACT_ERROR', 'Basic fact error', 'Recalls a multiplication or addition fact incorrectly although the method used is right.', 'OPS', 'Rebuild the fact from one you know (double, add one more group, use 10×) and practise it in short rounds.'),
  ('DIVISION_REMAINDER_ERROR', 'Remainder mishandled', 'Ignores the remainder, or writes it as a decimal or in the wrong place, in a division.', 'OPS', 'Check by multiplying back and adding the remainder; ask what the remainder means in the story.'),
  ('OPERATION_CHOICE_ERROR', 'Wrong operation chosen', 'Chooses addition, subtraction, multiplication or division that does not fit the situation in a word problem.', null, 'Retell the story in your own words, draw it, and ask what is being joined, taken away, shared or repeated.'),
  ('HCF_LCM_CONFUSION', 'HCF and LCM confused', 'Finds a common multiple when asked for a common factor, or the other way round.', 'OPS', 'List factors (numbers that divide in) and multiples (numbers that come out in the times table) separately for each number.'),
  ('ANGLE_TYPE_CONFUSION', 'Angle types confused', 'Mixes up acute, right, obtuse and straight angles, or reads the wrong size from a turn.', 'MEA', 'Compare every angle with a right angle (a corner of a page): smaller is acute, bigger is obtuse.'),
  ('AVERAGE_CONFUSION', 'Mean, median or mode confused', 'Uses the wrong measure of the data (the most common value instead of the average, or the middle instead of the total shared out).', 'REL', 'Say what each word means in plain words: mode is the most common, median the middle one in order, mean is the total shared equally.'),
  ('FRACTION_NOTATION_CONFUSION', 'Fraction written or read upside down', 'Swaps the numerator and the denominator when writing or reading a fraction (three quarters as 4/3).', 'NUM', 'The bottom number names the kind of part (quarters, fifths); the top number counts how many of them there are. Say the fraction in words before writing it.'),
  ('PART_WHOLE_CONFUSION', 'Part compared with part, not with the whole', 'Writes the shaded parts over the unshaded parts instead of over all the equal parts (3 shaded and 5 not shaded as 3/5, not 3/8).', 'NUM', 'Count ALL the equal parts first: that is the denominator. Then count the shaded ones: that is the numerator.'),
  ('FRACTION_COMPONENT_COMPARISON', 'Numerators and denominators compared separately', 'Compares fractions by looking at the tops and bottoms as separate whole numbers (thinks 2/3 is bigger than 3/8 because 3 is bigger than 2, or ignores the denominators).', 'NUM', 'Rewrite both fractions with the same denominator, or draw them on equal strips, and then compare the numerators.'),
  ('EQUIVALENT_FRACTION_ADDITIVE_ERROR', 'Adds instead of multiplying to make an equivalent fraction', 'Adds the same number to the numerator and the denominator (1/2 → 3/4) instead of multiplying both by the same number.', 'NUM', 'Equivalent fractions name the same amount: both numbers are multiplied (or divided) by the same number. Check with fraction strips.'),
  ('MIXED_IMPROPER_CONVERSION_ERROR', 'Mixed number and improper fraction mixed up', 'Converts between mixed numbers and improper fractions wrongly: forgets to multiply the whole number by the denominator, or adds the whole number to the numerator.', 'NUM', 'Think of the wholes as parts: each whole holds as many parts as the denominator says. Count all the parts, then write them over the denominator.'),
  ('PERCENT_CONVERSION_ERROR', 'Percentage conversion error', 'Changes between fractions, decimals and percentages with the wrong factor (writes 1/4 as 14% or 4%).', 'NUM', 'A percentage is a fraction out of 100. Make the denominator 100 first (or divide 100 by the denominator) and read off the numerator.'),
  ('FRACTION_MULTIPLICATION_ERROR', 'Fraction multiplication error', 'Finds a common denominator before multiplying, adds the numerators, or multiplies only the numerators.', 'OPS', 'To multiply fractions, multiply the numerators together and the denominators together. A common denominator is only needed for adding and subtracting.'),
  ('FRACTION_OF_QUANTITY_ERROR', 'Stops after dividing by the denominator', 'Finds one part (divides by the denominator) but forgets to take the number of parts the numerator asks for, or does it the wrong way round.', 'OPS', 'Divide by the denominator to find one equal part, then multiply by the numerator to take that many parts.'),
  ('MULTIPLICATION_PLACE_ERROR', 'Partial products misplaced in long multiplication', 'Forgets the zero placeholder (or misaligns the rows) when multiplying by a tens digit, so the partial product is ten times too small.', 'OPS', 'Multiplying by the tens digit is really multiplying by tens: write a 0 in the ones place of that row first.'),
  ('PROFIT_LOSS_CONFUSION', 'Profit and loss confused', 'Calls a loss a profit (or the other way round), or subtracts the selling price and the cost price in the wrong order.', 'MEA', 'Compare the selling price with the cost price: more than the cost is a profit, less is a loss. Always take the smaller from the bigger.'),
  ('RATE_FORMULA_ERROR', 'Speed, distance and time formula wrong', 'Uses the wrong operation for speed, distance or time (for example multiplies distance by time to find speed).', 'MEA', 'Use the triangle D / (S × T): cover what you want to find. Speed is distance shared by time; distance is speed times time.'),
  ('ANGLE_SUM_ERROR', 'Wrong total for angles', 'Uses the wrong total when finding a missing angle (360° on a straight line instead of 180°, or 180° around a point).', 'MEA', 'Angles on a straight line make a half turn (180°), angles at a point make a full turn (360°), angles in a triangle make 180°. Find the right total first, then subtract.'),
  ('PERIMETER_SIDES_MISSED', 'Not all sides added for the perimeter', 'Adds only the sides that are marked (for example length + width of a rectangle) and misses the equal sides that are not marked.', 'MEA', 'Walk round the shape with a finger and count every side. Mark each side that has an equal partner and add all of them.'),
  ('CLOCK_READING_ERROR', 'Clock hands misread', 'Reads the minute hand as hours or counts the number the hand points at as minutes (reads 9 as 9 minutes), or reads the wrong hour when the hour hand is between two numbers.', 'MEA', 'Look at the short hand for the hour, then at the long hand: each number on the clock face is 5 minutes, so count in fives.'),
  ('RULER_START_ERROR', 'Length read from the wrong starting mark', 'Reads the mark where the line ends instead of working out its length when the line does not start at 0.', 'MEA', 'A length is the distance from where the line starts to where it ends: read both marks and find the difference, or slide the line back to 0.'),
  ('VOLUME_AREA_CONFUSION', 'Volume found as area or by adding', 'Multiplies only two of the three measurements (the area of one face) or adds the length, width and height instead of multiplying all three.', 'MEA', 'Volume counts the cubes that fill the solid: layers of length × width, and as many layers as the height. Multiply all three measurements.')
on conflict (code) do update set
  name = excluded.name, description = excluded.description,
  topic_code = excluded.topic_code, remediation = excluded.remediation;
